### ISSUE TITLE
e2l1 - Player 1 controlling all players camera in glider

### ISSUE THREAD

**Issue by ChannelDaniila** [Chrissstrahl/hzm-mohaa-coop-mod#31]
At mission start, where we and another guys sitting in a glider, player 1 controlling all players camera (Other players can't move camera)

**Comment by 1337Smithy** [comment]
Bug happened because I was passing in camera entity to 'target', which would translate to the targetname string 'gliderCamera'.
As all cameras have the same targetname, it was just selecting the first in the targetname array (thus, first player's camera).
Now I temporarily rename camera to that of the targetname + player entnum then set that as the target. 

Needs testing with multiple players.

Fix: https://github.com/Chrissstrahl/hzm-mohaa-coop-mod/commit/8d48e324ec3ec6877b84a5dfc5e5bf1ae4520c0a

**Comment by ChannelDaniila** [comment]
Fixed.
