### ISSUE TITLE
e1l2 - Allied soldiers not moving

### ISSUE THREAD

**Issue by ChannelDaniila** [Chrissstrahl/hzm-mohaa-coop-mod#61]
Our rangers not moving and just staying!
[Image](https://user-images.githubusercontent.com/75738095/103091632-6a749600-45fd-11eb-9bdd-c3dc9853dff2.png)

**Comment by 1337Smithy** [comment]
Think this is due to friendly rewrite. level.coop_player seems to be NULL so it's forever waiting in friendly.scr.

**Comment by 1337Smithy** [comment]
I think this needs to be for Chrissstrahl to sort. It's because friendtype = 1 is assumed to be only for players, but this doesn't seem to be true. In e1l2 the $infantry that are meant to follow the jeep in the intro are given a destination of an entity that isn't a player. Thus, level.coop_player is NULL and gets stuck. The best solution would be to implement some way of knowing whether the designer originally intended them to follow a player or some other entity, if it doesn't already exist, so we can then check for valid players every time or not. 

Where it gets stuck is:
`				while(!level.coop_player || !($player)){
					wait 2
				}
`

**Comment by 1337Smithy** [comment]
This will need testing on as many friendly AI missions as possible, but initial testing passed.

**Comment by ChannelDaniila** [comment]
Tested, fix is working.
